# Generated by Django 3.0 on 2019-12-05 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apishoe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoecolor',
            old_name='color',
            new_name='color_style',
        ),
    ]
